// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUpze-2d9wChfDZeAiZl7P3KkLoYLlhjA',
    appId: '1:371258350307:web:8f8f567dceaeeb970083d6',
    messagingSenderId: '371258350307',
    projectId: 'gabong-12117',
    authDomain: 'gabong-12117.firebaseapp.com',
    storageBucket: 'gabong-12117.firebasestorage.app',
    measurementId: 'G-7CNK3WZM8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1tTgKabNb8Lv0n_snHxOM_fluDLL7DC8',
    appId: '1:371258350307:android:0f2f8ff99e674eb90083d6',
    messagingSenderId: '371258350307',
    projectId: 'gabong-12117',
    storageBucket: 'gabong-12117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_v22DyD6MqXClrNYQbfQl2_fsfWWzqdw',
    appId: '1:371258350307:ios:0f60668b3ea680e00083d6',
    messagingSenderId: '371258350307',
    projectId: 'gabong-12117',
    storageBucket: 'gabong-12117.firebasestorage.app',
    iosBundleId: 'com.example.gabongV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_v22DyD6MqXClrNYQbfQl2_fsfWWzqdw',
    appId: '1:371258350307:ios:0f60668b3ea680e00083d6',
    messagingSenderId: '371258350307',
    projectId: 'gabong-12117',
    storageBucket: 'gabong-12117.firebasestorage.app',
    iosBundleId: 'com.example.gabongV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUpze-2d9wChfDZeAiZl7P3KkLoYLlhjA',
    appId: '1:371258350307:web:ff94b7e569b1b8990083d6',
    messagingSenderId: '371258350307',
    projectId: 'gabong-12117',
    authDomain: 'gabong-12117.firebaseapp.com',
    storageBucket: 'gabong-12117.firebasestorage.app',
    measurementId: 'G-XD8M359NGV',
  );

}